# Dataset Extraction from Website

## Top 1000 Street Foods

### Download the dataset

In [1]:
"""import kagglehub

# Download latest version
path = kagglehub.dataset_download("benjnb/global-street-food-dataset")

print("Path to dataset files:", path)"""

'import kagglehub\n\n# Download latest version\npath = kagglehub.dataset_download("benjnb/global-street-food-dataset")\n\nprint("Path to dataset files:", path)'

In [2]:
filepath= "C:\\Users\\hp\\Git\\Python-Practice\\Street Food Analysis\\raw data\\global_street_food.csv"
outputpath= "C:\\Users\\hp\\Git\\Python-Practice\\Street Food Analysis\\files\\"

In [3]:
import pandas as pd
import os
df= pd.read_csv(filepath,header=0)
display(df)

,Dish Name,Country,Region/City,Ingredients,Description,Cooking Method,Typical Price (USD),Vegetarian
0,Takoyaki,Japan,Osaka,"Octopus, Flour Batter, Bonito Flakes, Green On...","Crispy and hot, often served with sauces or ch...",Fried,3.28,No
1,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,2.37,Yes
2,Funnel Cake,USA,Texas,"Batter, Sugar, Oil","Crispy and hot, often served with sauces or ch...",Fried,2.78,Yes
3,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,1.89,No
4,Pad Thai,Thailand,Bangkok,"Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,3.48,Yes
...,...,...,...,...,...,...,...,...
4495,Koshari,Egypt,Cairo,"Lentils, Rice, Pasta, Tomato Sauce, Onions",A hearty mix of grains topped with spicy tomat...,Boiled,2.80,Yes
4496,Koshari,Egypt,Cairo,"Lentils, Rice, Pasta, Tomato Sauce, Onions",A hearty mix of grains topped with spicy tomat...,Boiled,2.80,Yes
4497,Koshari,Egypt,Cairo,"Lentils, Rice, Pasta, Tomato Sauce, Onions",A hearty mix of grains topped with spicy tomat...,Boiled,2.80,Yes
4498,Koshari,Egypt,Cairo,"Lentils, Rice, Pasta, Tomato Sauce, Onions",A hearty mix of grains topped with spicy tomat...,Boiled,2.80,Yes
4499,Suya,Nigeria,Lagos,"Beef, Spices, Skewers",Spicy meat skewers grilled to perfection.,Grilled,2.50,No

In [4]:
#Country and citys in the Dataset

cc_df=df[["Country","Region/City"]].drop_duplicates().sort_values(by="Country",ascending=True)
cc_df=cc_df.reset_index(drop=True)

#Counts
country_count= cc_df["Country"].nunique()
city_count= cc_df["Region/City"].nunique()
pair_count= cc_df.shape[0]

counts_dict = {
    "Country": country_count,
    "City": city_count,
    "Country city pairs": pair_count
}

Statistics = {
    "Counts": {
        "Country_city_Dimension": counts_dict
    }
}

print(Statistics)
print(cc_df)

{'Counts': {'Country_city_Dimension': {'Country': 11, 'City': 25, 'Country city pairs': 25}}}
         Country   Region/City
0          Egypt         Cairo
1          India        Mumbai
2          India       Kolkata
3          India         Delhi
4         Israel      Tel Aviv
5          Japan     Hiroshima
6          Japan         Tokyo
7          Japan         Osaka
8          Japan         Kyoto
9        Lebanon        Beirut
10       Lebanon       Tripoli
11        Mexico   Guadalajara
12        Mexico        Puebla
13        Mexico   Mexico City
14       Nigeria         Lagos
15  South Africa        Durban
16      Thailand       Bangkok
17      Thailand    Chiang Mai
18      Thailand     Ayutthaya
19        Turkey        Ankara
20        Turkey      Istanbul
21        Turkey         Izmir
22           USA      New York
23           USA         Texas
24           USA  Philadelphia

In [5]:
all_ingredients= ", ".join(df["Ingredients"].str.split(", ").explode())
display(all_ingredients)

"Octopus, Flour Batter, Bonito Flakes, Green Onions, Potato, Spices, Bread Bun, Chutney, Batter, Sugar, Oil, Flatbread, Egg, Chicken, Onions, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Potato, Spices, Bread Bun, Chutney, Semolina, Tamarind, Chickpeas, Spices, Flour, Red Bean Paste, Dough, Spinach, Cheese, Lamb Intestines, Spices, Bread, Semolina, Tamarind, Chickpeas, Spices, Potato, Spices, Bread Bun, Chutney, Roti, Cotton Candy, Potato, Spices, Bread Bun, Chutney, Noodles, Pork, Cabbage, Yakisoba Sauce, Tortilla, Cheese, Mushrooms, Flour, Red Bean Paste, Roti, Cotton Candy, Semolina, Tamarind, Chickpeas, Spices, Semolina, Tamarind, Chickpeas, Spices, Potato, Spices, Bread Bun, Chutney, Corn, Mayo, Cheese, Chili Powder, Dough, Spinach, Cheese, Sausage, Bun, Mustard, Ketchup, Lamb Intestines, Spices, Bread, Octopus, Flour Batter, Bonito Flakes, Green Onions, Potato, Spices, Bread Bun, Chutney, Semolina, Tamarind, Chickpeas, Spices, Pork, Pineapple, Onions, Cilantro, Noodles, Pork, Cabbage, Yakisoba Sauce, Dough, Spinach, Cheese, Noodles, Pork, Cabbage, Yakisoba Sauce, Lamb Intestines, Spices, Bread, Pork, Pineapple, Onions, Cilantro, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Tortilla, Cheese, Mushrooms, Sausage, Bun, Mustard, Ketchup, Semolina, Tamarind, Chickpeas, Spices, Flour, Sesame Seeds, Yeast, Flatbread, Egg, Chicken, Onions, Chutney, Batter, Sugar, Oil, Flour, Red Bean Paste, Pork, Garlic, Soy Sauce, Sugar, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Corn, Mayo, Cheese, Chili Powder, Flour, Sesame Seeds, Yeast, Dough, Spinach, Cheese, Pork, Pineapple, Onions, Cilantro, Pork, Pineapple, Onions, Cilantro, Pork, Pineapple, Onions, Cilantro, Tortilla, Cheese, Mushrooms, Semolina, Tamarind, Chickpeas, Spices, Noodles, Pork, Cabbage, Yakisoba Sauce, Flour, Sesame Seeds, Yeast, Potato, Spices, Bread Bun, Chutney, Beef, Cheese, Roll, Onions, Dough, Spinach, Cheese, Flour, Sesame Seeds, Yeast, Dough, Spinach, Cheese, Corn, Mayo, Cheese, Chili Powder, Pork, Garlic, Soy Sauce, Sugar, Semolina, Tamarind, Chickpeas, Spices, Flour, Sesame Seeds, Yeast, Flour, Sesame Seeds, Yeast, Dough, Spinach, Cheese, Pork, Pineapple, Onions, Cilantro, Flatbread, Egg, Chicken, Onions, Chutney, Batter, Sugar, Oil, Dough, Spinach, Cheese, Batter, Sugar, Oil, Beef, Cheese, Roll, Onions, Roti, Cotton Candy, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flatbread, Egg, Chicken, Onions, Chutney, Noodles, Pork, Cabbage, Yakisoba Sauce, Pork, Pineapple, Onions, Cilantro, Pork, Pineapple, Onions, Cilantro, Semolina, Tamarind, Chickpeas, Spices, Batter, Sugar, Oil, Flatbread, Egg, Chicken, Onions, Chutney, Roti, Cotton Candy, Dough, Spinach, Cheese, Flatbread, Egg, Chicken, Onions, Chutney, Semolina, Tamarind, Chickpeas, Spices, Dough, Spinach, Cheese, Flour, Sesame Seeds, Yeast, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Roti, Cotton Candy, Roti, Cotton Candy, Noodles, Pork, Cabbage, Yakisoba Sauce, Roti, Cotton Candy, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Pork, Garlic, Soy Sauce, Sugar, Octopus, Flour Batter, Bonito Flakes, Green Onions, Pork, Garlic, Soy Sauce, Sugar, Pork, Pineapple, Onions, Cilantro, Flatbread, Egg, Chicken, Onions, Chutney, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Lamb Intestines, Spices, Bread, Flour, Sesame Seeds, Yeast, Flour, Sesame Seeds, Yeast, Flour, Red Bean Paste, Batter, Sugar, Oil, Tortilla, Cheese, Mushrooms, Corn, Mayo, Cheese, Chili Powder, Flour, Sesame Seeds, Yeast, Dough, Spinach, Cheese, Beef, Cheese, Roll, Onions, Dough, Spinach, Cheese, Flour, Sesame Seeds, Yeast, Semolina, Tamarind, Chickpeas, Spices, Octopus, Flour Batter, Bonito Flakes, Green Onions, Lamb Intestines, Spices, Bread, Flour, Red Bean Paste, Corn, Mayo, Cheese, Chili Powder, Semolina, Tamarind, Chickpeas, Spices, Potato, Spices, Bread Bun, Chutney, Roti, Cotton Candy, Tortilla, Cheese, Mushrooms, Flour, Red Bean Paste, Beef, Cheese, Roll, Onions, Flatbread, Egg, Chicken, Onions, Chutney, Semolina, Tamarind, Chickpeas, Spices, Pork, Garlic, Soy Sauce, Sugar, Flour, Red Bean Paste, Lamb Intestines, Spices, Bread, Semolina, Tamarind, Chickpeas, Spices, Flour, Sesame Seeds, Yeast, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Noodles, Pork, Cabbage, Yakisoba Sauce, Flour, Red Bean Paste, Beef, Cheese, Roll, Onions, Octopus, Flour Batter, Bonito Flakes, Green Onions, Tortilla, Cheese, Mushrooms, Lamb Intestines, Spices, Bread, Flatbread, Egg, Chicken, Onions, Chutney, Beef, Cheese, Roll, Onions, Flatbread, Egg, Chicken, Onions, Chutney, Semolina, Tamarind, Chickpeas, Spices, Pork, Garlic, Soy Sauce, Sugar, Roti, Cotton Candy, Flour, Sesame Seeds, Yeast, Beef, Cheese, Roll, Onions, Semolina, Tamarind, Chickpeas, Spices, Roti, Cotton Candy, Semolina, Tamarind, Chickpeas, Spices, Corn, Mayo, Cheese, Chili Powder, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Flour, Red Bean Paste, Flour, Sesame Seeds, Yeast, Tortilla, Cheese, Mushrooms, Corn, Mayo, Cheese, Chili Powder, Corn, Mayo, Cheese, Chili Powder, Potato, Spices, Bread Bun, Chutney, Semolina, Tamarind, Chickpeas, Spices, Tortilla, Cheese, Mushrooms, Semolina, Tamarind, Chickpeas, Spices, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Beef, Cheese, Roll, Onions, Tortilla, Cheese, Mushrooms, Pork, Garlic, Soy Sauce, Sugar, Batter, Sugar, Oil, Pork, Garlic, Soy Sauce, Sugar, Sausage, Bun, Mustard, Ketchup, Batter, Sugar, Oil, Dough, Spinach, Cheese, Roti, Cotton Candy, Sausage, Bun, Mustard, Ketchup, Potato, Spices, Bread Bun, Chutney, Tortilla, Cheese, Mushrooms, Sausage, Bun, Mustard, Ketchup, Flour, Sesame Seeds, Yeast, Dough, Spinach, Cheese, Flour, Sesame Seeds, Yeast, Pork, Pineapple, Onions, Cilantro, Dough, Spinach, Cheese, Tortilla, Cheese, Mushrooms, Potato, Spices, Bread Bun, Chutney, Beef, Cheese, Roll, Onions, Potato, Spices, Bread Bun, Chutney, Semolina, Tamarind, Chickpeas, Spices, Flour, Sesame Seeds, Yeast, Lamb Intestines, Spices, Bread, Potato, Spices, Bread Bun, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Sesame Seeds, Yeast, Flatbread, Egg, Chicken, Onions, Chutney, Flour, Red Bean Paste, Dough, Spinach, Cheese, Beef, Cheese, Roll, Onions, Corn, Mayo, Cheese, Chili Powder, Flour, Sesame Seeds, Yeast, Flour, Sesame Seeds, Yeast, Pork, Garlic, Soy Sauce, Sugar, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Sesame Seeds, Yeast, Beef, Cheese, Roll, Onions, Dough, Spinach, Cheese, Semolina, Tamarind, Chickpeas, Spices, Sausage, Bun, Mustard, Ketchup, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Potato, Spices, Bread Bun, Chutney, Pork, Pineapple, Onions, Cilantro, Potato, Spices, Bread Bun, Chutney, Pork, Pineapple, Onions, Cilantro, Flatbread, Egg, Chicken, Onions, Chutney, Corn, Mayo, Cheese, Chili Powder, Noodles, Pork, Cabbage, Yakisoba Sauce, Pork, Garlic, Soy Sauce, Sugar, Sausage, Bun, Mustard, Ketchup, Flour, Sesame Seeds, Yeast, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Sesame Seeds, Yeast, Flour, Red Bean Paste, Potato, Spices, Bread Bun, Chutney, Flatbread, Egg, Chicken, Onions, Chutney, Flour, Red Bean Paste, Flour, Sesame Seeds, Yeast, Semolina, Tamarind, Chickpeas, Spices, Semolina, Tamarind, Chickpeas, Spices, Flour, Sesame Seeds, Yeast, Roti, Cotton Candy, Dough, Spinach, Cheese, Sausage, Bun, Mustard, Ketchup, Flour, Red Bean Paste, Sausage, Bun, Mustard, Ketchup, Lamb Intestines, Spices, Bread, Flatbread, Egg, Chicken, Onions, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Sausage, Bun, Mustard, Ketchup, Tortilla, Cheese, Mushrooms, Beef, Cheese, Roll, Onions, Flour, Sesame Seeds, Yeast, Batter, Sugar, Oil, Flour, Red Bean Paste, Tortilla, Cheese, Mushrooms, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flatbread, Egg, Chicken, Onions, Chutney, Beef, Cheese, Roll, Onions, Sausage, Bun, Mustard, Ketchup, Sausage, Bun, Mustard, Ketchup, Pork, Garlic, Soy Sauce, Sugar, Corn, Mayo, Cheese, Chili Powder, Noodles, Pork, Cabbage, Yakisoba Sauce, Tortilla, Cheese, Mushrooms, Flour, Red Bean Paste, Flour, Sesame Seeds, Yeast, Roti, Cotton Candy, Noodles, Pork, Cabbage, Yakisoba Sauce, Batter, Sugar, Oil, Potato, Spices, Bread Bun, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Red Bean Paste, Corn, Mayo, Cheese, Chili Powder, Semolina, Tamarind, Chickpeas, Spices, Pork, Pineapple, Onions, Cilantro, Pork, Garlic, Soy Sauce, Sugar, Octopus, Flour Batter, Bonito Flakes, Green Onions, Pork, Pineapple, Onions, Cilantro, Batter, Sugar, Oil, Pork, Pineapple, Onions, Cilantro, Roti, Cotton Candy, Tortilla, Cheese, Mushrooms, Sausage, Bun, Mustard, Ketchup, Dough, Spinach, Cheese, Lamb Intestines, Spices, Bread, Dough, Spinach, Cheese, Potato, Spices, Bread Bun, Chutney, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flour, Red Bean Paste, Beef, Cheese, Roll, Onions, Pork, Pineapple, Onions, Cilantro, Octopus, Flour Batter, Bonito Flakes, Green Onions, Pork, Pineapple, Onions, Cilantro, Batter, Sugar, Oil, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Octopus, Flour Batter, Bonito Flakes, Green Onions, Beef, Cheese, Roll, Onions, Pork, Pineapple, Onions, Cilantro, Beef, Cheese, Roll, Onions, Semolina, Tamarind, Chickpeas, Spices, Beef, Cheese, Roll, Onions, Corn, Mayo, Cheese, Chili Powder, Batter, Sugar, Oil, Roti, Cotton Candy, Potato, Spices, Bread Bun, Chutney, Flatbread, Egg, Chicken, Onions, Chutney, Roti, Cotton Candy, Roti, Cotton Candy, Flour, Sesame Seeds, Yeast, Flour, Sesame Seeds, Yeast, Batter, Sugar, Oil, Lamb Intestines, Spices, Bread, Pork, Garlic, Soy Sauce, Sugar, Corn, Mayo, Cheese, Chili Powder, Semolina, Tamarind, Chickpeas, Spices, Sausage, Bun, Mustard, Ketchup, Tortilla, Cheese, Mushrooms, Flour, Sesame Seeds, Yeast, Flatbread, Egg, Chicken, Onions, Chutney, Tortilla, Cheese, Mushrooms, Tortilla, Cheese, Mushrooms, Flour, Sesame Seeds, Yeast, Semolina, Tamarind, Chickpeas, Spices, Potato, Spices, Bread Bun, Chutney, Flour, Red Bean Paste, Noodles, Pork, Cabbage, Yakisoba Sauce, Beef, Cheese, Roll, Onions, Semolina, Tamarind, Chickpeas, Spices, Pork, Pineapple, Onions, Cilantro, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Sesame Seeds, Yeast, Sausage, Bun, Mustard, Ketchup, Beef, Cheese, Roll, Onions, Semolina, Tamarind, Chickpeas, Spices, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Beef, Cheese, Roll, Onions, Pork, Garlic, Soy Sauce, Sugar, Octopus, Flour Batter, Bonito Flakes, Green Onions, Batter, Sugar, Oil, Corn, Mayo, Cheese, Chili Powder, Dough, Spinach, Cheese, Lamb Intestines, Spices, Bread, Roti, Cotton Candy, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Batter, Sugar, Oil, Flatbread, Egg, Chicken, Onions, Chutney, Corn, Mayo, Cheese, Chili Powder, Noodles, Pork, Cabbage, Yakisoba Sauce, Dough, Spinach, Cheese, Noodles, Pork, Cabbage, Yakisoba Sauce, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flour, Sesame Seeds, Yeast, Corn, Mayo, Cheese, Chili Powder, Roti, Cotton Candy, Flour, Sesame Seeds, Yeast, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Semolina, Tamarind, Chickpeas, Spices, Dough, Spinach, Cheese, Flatbread, Egg, Chicken, Onions, Chutney, Potato, Spices, Bread Bun, Chutney, Pork, Pineapple, Onions, Cilantro, Tortilla, Cheese, Mushrooms, Flatbread, Egg, Chicken, Onions, Chutney, Flour, Red Bean Paste, Octopus, Flour Batter, Bonito Flakes, Green Onions, Sausage, Bun, Mustard, Ketchup, Flatbread, Egg, Chicken, Onions, Chutney, Tortilla, Cheese, Mushrooms, Octopus, Flour Batter, Bonito Flakes, Green Onions, Pork, Pineapple, Onions, Cilantro, Flour, Sesame Seeds, Yeast, Lamb Intestines, Spices, Bread, Octopus, Flour Batter, Bonito Flakes, Green Onions, Sausage, Bun, Mustard, Ketchup, Beef, Cheese, Roll, Onions, Tortilla, Cheese, Mushrooms, Noodles, Pork, Cabbage, Yakisoba Sauce, Beef, Cheese, Roll, Onions, Beef, Cheese, Roll, Onions, Pork, Pineapple, Onions, Cilantro, Flour, Sesame Seeds, Yeast, Flour, Red Bean Paste, Semolina, Tamarind, Chickpeas, Spices, Roti, Cotton Candy, Roti, Cotton Candy, Flour, Sesame Seeds, Yeast, Roti, Cotton Candy, Dough, Spinach, Cheese, Flour, Sesame Seeds, Yeast, Potato, Spices, Bread Bun, Chutney, Flatbread, Egg, Chicken, Onions, Chutney, Beef, Cheese, Roll, Onions, Sausage, Bun, Mustard, Ketchup, Batter, Sugar, Oil, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Batter, Sugar, Oil, Dough, Spinach, Cheese, Lamb Intestines, Spices, Bread, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flatbread, Egg, Chicken, Onions, Chutney, Flour, Red Bean Paste, Beef, Cheese, Roll, Onions, Flour, Sesame Seeds, Yeast, Flatbread, Egg, Chicken, Onions, Chutney, Potato, Spices, Bread Bun, Chutney, Batter, Sugar, Oil, Potato, Spices, Bread Bun, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Red Bean Paste, Flour, Red Bean Paste, Flour, Red Bean Paste, Pork, Garlic, Soy Sauce, Sugar, Tortilla, Cheese, Mushrooms, Batter, Sugar, Oil, Batter, Sugar, Oil, Pork, Garlic, Soy Sauce, Sugar, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Pork, Pineapple, Onions, Cilantro, Tortilla, Cheese, Mushrooms, Flatbread, Egg, Chicken, Onions, Chutney, Beef, Cheese, Roll, Onions, Sausage, Bun, Mustard, Ketchup, Octopus, Flour Batter, Bonito Flakes, Green Onions, Lamb Intestines, Spices, Bread, Sausage, Bun, Mustard, Ketchup, Dough, Spinach, Cheese, Pork, Pineapple, Onions, Cilantro, Beef, Cheese, Roll, Onions, Tortilla, Cheese, Mushrooms, Roti, Cotton Candy, Pork, Garlic, Soy Sauce, Sugar, Lamb Intestines, Spices, Bread, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flatbread, Egg, Chicken, Onions, Chutney, Noodles, Pork, Cabbage, Yakisoba Sauce, Flour, Red Bean Paste, Noodles, Pork, Cabbage, Yakisoba Sauce, Roti, Cotton Candy, Tortilla, Cheese, Mushrooms, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Dough, Spinach, Cheese, Tortilla, Cheese, Mushrooms, Potato, Spices, Bread Bun, Chutney, Flatbread, Egg, Chicken, Onions, Chutney, Batter, Sugar, Oil, Pork, Garlic, Soy Sauce, Sugar, Noodles, Pork, Cabbage, Yakisoba Sauce, Sausage, Bun, Mustard, Ketchup, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Octopus, Flour Batter, Bonito Flakes, Green Onions, Dough, Spinach, Cheese, Lamb Intestines, Spices, Bread, Potato, Spices, Bread Bun, Chutney, Corn, Mayo, Cheese, Chili Powder, Semolina, Tamarind, Chickpeas, Spices, Flour, Red Bean Paste, Dough, Spinach, Cheese, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flour, Sesame Seeds, Yeast, Semolina, Tamarind, Chickpeas, Spices, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Dough, Spinach, Cheese, Pork, Pineapple, Onions, Cilantro, Lamb Intestines, Spices, Bread, Corn, Mayo, Cheese, Chili Powder, Octopus, Flour Batter, Bonito Flakes, Green Onions, Pork, Garlic, Soy Sauce, Sugar, Pork, Pineapple, Onions, Cilantro, Pork, Pineapple, Onions, Cilantro, Dough, Spinach, Cheese, Flour, Red Bean Paste, Flour, Red Bean Paste, Roti, Cotton Candy, Tortilla, Cheese, Mushrooms, Pork, Garlic, Soy Sauce, Sugar, Potato, Spices, Bread Bun, Chutney, Tortilla, Cheese, Mushrooms, Tortilla, Cheese, Mushrooms, Dough, Spinach, Cheese, Pork, Garlic, Soy Sauce, Sugar, Octopus, Flour Batter, Bonito Flakes, Green Onions, Batter, Sugar, Oil, Flatbread, Egg, Chicken, Onions, Chutney, Pork, Garlic, Soy Sauce, Sugar, Dough, Spinach, Cheese, Pork, Garlic, Soy Sauce, Sugar, Tortilla, Cheese, Mushrooms, Batter, Sugar, Oil, Beef, Cheese, Roll, Onions, Semolina, Tamarind, Chickpeas, Spices, Roti, Cotton Candy, Dough, Spinach, Cheese, Pork, Garlic, Soy Sauce, Sugar, Corn, Mayo, Cheese, Chili Powder, Semolina, Tamarind, Chickpeas, Spices, Potato, Spices, Bread Bun, Chutney, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flour, Sesame Seeds, Yeast, Semolina, Tamarind, Chickpeas, Spices, Beef, Cheese, Roll, Onions, Dough, Spinach, Cheese, Semolina, Tamarind, Chickpeas, Spices, Dough, Spinach, Cheese, Semolina, Tamarind, Chickpeas, Spices, Octopus, Flour Batter, Bonito Flakes, Green Onions, Lamb Intestines, Spices, Bread, Octopus, Flour Batter, Bonito Flakes, Green Onions, Roti, Cotton Candy, Dough, Spinach, Cheese, Batter, Sugar, Oil, Semolina, Tamarind, Chickpeas, Spices, Noodles, Pork, Cabbage, Yakisoba Sauce, Octopus, Flour Batter, Bonito Flakes, Green Onions, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Dough, Spinach, Cheese, Potato, Spices, Bread Bun, Chutney, Potato, Spices, Bread Bun, Chutney, Semolina, Tamarind, Chickpeas, Spices, Flour, Red Bean Paste, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Corn, Mayo, Cheese, Chili Powder, Flour, Red Bean Paste, Batter, Sugar, Oil, Noodles, Pork, Cabbage, Yakisoba Sauce, Roti, Cotton Candy, Potato, Spices, Bread Bun, Chutney, Flour, Red Bean Paste, Batter, Sugar, Oil, Dough, Spinach, Cheese, Pork, Garlic, Soy Sauce, Sugar, Potato, Spices, Bread Bun, Chutney, Batter, Sugar, Oil, Potato, Spices, Bread Bun, Chutney, Semolina, Tamarind, Chickpeas, Spices, Dough, Spinach, Cheese, Roti, Cotton Candy, Tortilla, Cheese, Mushrooms, Corn, Mayo, Cheese, Chili Powder, Sausage, Bun, Mustard, Ketchup, Sausage, Bun, Mustard, Ketchup, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Sesame Seeds, Yeast, Sausage, Bun, Mustard, Ketchup, Pork, Pineapple, Onions, Cilantro, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Beef, Cheese, Roll, Onions, Pork, Garlic, Soy Sauce, Sugar, Corn, Mayo, Cheese, Chili Powder, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flour, Red Bean Paste, Roti, Cotton Candy, Beef, Cheese, Roll, Onions, Dough, Spinach, Cheese, Noodles, Pork, Cabbage, Yakisoba Sauce, Potato, Spices, Bread Bun, Chutney, Roti, Cotton Candy, Sausage, Bun, Mustard, Ketchup, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flour, Red Bean Paste, Flatbread, Egg, Chicken, Onions, Chutney, Corn, Mayo, Cheese, Chili Powder, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Flatbread, Egg, Chicken, Onions, Chutney, Octopus, Flour Batter, Bonito Flakes, Green Onions, Flour, Red Bean Paste, Flour, Red Bean Paste, Flatbread, Egg, Chicken, Onions, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Lamb Intestines, Spices, Bread, Pork, Garlic, Soy Sauce, Sugar, Pork, Garlic, Soy Sauce, Sugar, Semolina, Tamarind, Chickpeas, Spices, Semolina, Tamarind, Chickpeas, Spices, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Octopus, Flour Batter, Bonito Flakes, Green Onions, Dough, Spinach, Cheese, Flatbread, Egg, Chicken, Onions, Chutney, Dough, Spinach, Cheese, Noodles, Pork, Cabbage, Yakisoba Sauce, Corn, Mayo, Cheese, Chili Powder, Tortilla, Cheese, Mushrooms, Pork, Pineapple, Onions, Cilantro, Flour, Red Bean Paste, Flour, Red Bean Paste, Sausage, Bun, Mustard, Ketchup, Noodles, Pork, Cabbage, Yakisoba Sauce, Potato, Spices, Bread Bun, Chutney, Noodles, Pork, Cabbage, Yakisoba Sauce, Flour, Red Bean Paste, Tortilla, Cheese, Mushrooms, Semolina, Tamarind, Chickpeas, Spices, Semolina, Tamarind, Chickpeas, Spices, Batter, Sugar, Oil, Semolina, Tamarind, Chickpeas, Spices, Octopus, Flour Batter, Bonito Flakes, Green Onions, Sausage, Bun, Mustard, Ketchup, Corn, Mayo, Cheese, Chili Powder, Dough, Spinach, Cheese, Beef, Cheese, Roll, Onions, Flour, Red Bean Paste, Lamb Intestines, Spices, Bread, Corn, Mayo, Cheese, Chili Powder, Pork, Pineapple, Onions, Cilantro, Flour, Red Bean Paste, Flatbread, Egg, Chicken, Onions, Chutney, Roti, Cotton Candy, Flatbread, Egg, Chicken, Onions, Chutney, Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts, Pork, Garlic, Soy Sauce, Sugar, Roti, Cotton Candy, Lamb Intestines, Spices, Bread, Lamb Intestines, Spices, Bread, Corn, Mayo, Cheese, Chili Powder, Corn, Mayo, Cheese, Chili Powder, Potato, Spices, Bread Bun, Chutney, Batter, Sugar, Oil, Tortilla, Cheese, Mushrooms, Roti, Cotton Candy, Corn, Mayo, Cheese, Chili Powder, Flour, Red Bean Paste, Flour, Sesame Seeds, Y

In [6]:
#List of Ingredients
idf= [i for i in df["Ingredients"]]
print(idf)

['Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Potato, Spices, Bread Bun, Chutney', 'Batter, Sugar, Oil', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Potato, Spices, Bread Bun, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Red Bean Paste', 'Dough, Spinach, Cheese', 'Lamb Intestines, Spices, Bread', 'Semolina, Tamarind, Chickpeas, Spices', 'Potato, Spices, Bread Bun, Chutney', 'Roti, Cotton Candy', 'Potato, Spices, Bread Bun, Chutney', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Tortilla, Cheese, Mushrooms', 'Flour, Red Bean Paste', 'Roti, Cotton Candy', 'Semolina, Tamarind, Chickpeas, Spices', 'Semolina, Tamarind, Chickpeas, Spices', 'Potato, Spices, Bread Bun, Chutney', 'Corn, Mayo, Cheese, Chili Powder', 'Dough, Spinach, Cheese', 'Sausage, Bun, Mustard, Ketchup', 'Lamb Intestines, Spices, Bread', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Potato, Spices, Bread Bun, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Pork, Pineapple, Onions, Cilantro', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Dough, Spinach, Cheese', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Lamb Intestines, Spices, Bread', 'Pork, Pineapple, Onions, Cilantro', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Tortilla, Cheese, Mushrooms', 'Sausage, Bun, Mustard, Ketchup', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Sesame Seeds, Yeast', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Batter, Sugar, Oil', 'Flour, Red Bean Paste', 'Pork, Garlic, Soy Sauce, Sugar', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Corn, Mayo, Cheese, Chili Powder', 'Flour, Sesame Seeds, Yeast', 'Dough, Spinach, Cheese', 'Pork, Pineapple, Onions, Cilantro', 'Pork, Pineapple, Onions, Cilantro', 'Pork, Pineapple, Onions, Cilantro', 'Tortilla, Cheese, Mushrooms', 'Semolina, Tamarind, Chickpeas, Spices', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Flour, Sesame Seeds, Yeast', 'Potato, Spices, Bread Bun, Chutney', 'Beef, Cheese, Roll, Onions', 'Dough, Spinach, Cheese', 'Flour, Sesame Seeds, Yeast', 'Dough, Spinach, Cheese', 'Corn, Mayo, Cheese, Chili Powder', 'Pork, Garlic, Soy Sauce, Sugar', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Sesame Seeds, Yeast', 'Flour, Sesame Seeds, Yeast', 'Dough, Spinach, Cheese', 'Pork, Pineapple, Onions, Cilantro', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Batter, Sugar, Oil', 'Dough, Spinach, Cheese', 'Batter, Sugar, Oil', 'Beef, Cheese, Roll, Onions', 'Roti, Cotton Candy', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Pork, Pineapple, Onions, Cilantro', 'Pork, Pineapple, Onions, Cilantro', 'Semolina, Tamarind, Chickpeas, Spices', 'Batter, Sugar, Oil', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Roti, Cotton Candy', 'Dough, Spinach, Cheese', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Dough, Spinach, Cheese', 'Flour, Sesame Seeds, Yeast', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Roti, Cotton Candy', 'Roti, Cotton Candy', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Roti, Cotton Candy', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Pork, Garlic, Soy Sauce, Sugar', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Pineapple, Onions, Cilantro', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Lamb Intestines, Spices, Bread', 'Flour, Sesame Seeds, Yeast', 'Flour, Sesame Seeds, Yeast', 'Flour, Red Bean Paste', 'Batter, Sugar, Oil', 'Tortilla, Cheese, Mushrooms', 'Corn, Mayo, Cheese, Chili Powder', 'Flour, Sesame Seeds, Yeast', 'Dough, Spinach, Cheese', 'Beef, Cheese, Roll, Onions', 'Dough, Spinach, Cheese', 'Flour, Sesame Seeds, Yeast', 'Semolina, Tamarind, Chickpeas, Spices', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Lamb Intestines, Spices, Bread', 'Flour, Red Bean Paste', 'Corn, Mayo, Cheese, Chili Powder', 'Semolina, Tamarind, Chickpeas, Spices', 'Potato, Spices, Bread Bun, Chutney', 'Roti, Cotton Candy', 'Tortilla, Cheese, Mushrooms', 'Flour, Red Bean Paste', 'Beef, Cheese, Roll, Onions', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Pork, Garlic, Soy Sauce, Sugar', 'Flour, Red Bean Paste', 'Lamb Intestines, Spices, Bread', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Sesame Seeds, Yeast', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Flour, Red Bean Paste', 'Beef, Cheese, Roll, Onions', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Tortilla, Cheese, Mushrooms', 'Lamb Intestines, Spices, Bread', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Beef, Cheese, Roll, Onions', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Pork, Garlic, Soy Sauce, Sugar', 'Roti, Cotton Candy', 'Flour, Sesame Seeds, Yeast', 'Beef, Cheese, Roll, Onions', 'Semolina, Tamarind, Chickpeas, Spices', 'Roti, Cotton Candy', 'Semolina, Tamarind, Chickpeas, Spices', 'Corn, Mayo, Cheese, Chili Powder', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Flour, Red Bean Paste', 'Flour, Sesame Seeds, Yeast', 'Tortilla, Cheese, Mushrooms', 'Corn, Mayo, Cheese, Chili Powder', 'Corn, Mayo, Cheese, Chili Powder', 'Potato, Spices, Bread Bun, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Tortilla, Cheese, Mushrooms', 'Semolina, Tamarind, Chickpeas, Spices', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Beef, Cheese, Roll, Onions', 'Tortilla, Cheese, Mushrooms', 'Pork, Garlic, Soy Sauce, Sugar', 'Batter, Sugar, Oil', 'Pork, Garlic, Soy Sauce, Sugar', 'Sausage, Bun, Mustard, Ketchup', 'Batter, Sugar, Oil', 'Dough, Spinach, Cheese', 'Roti, Cotton Candy', 'Sausage, Bun, Mustard, Ketchup', 'Potato, Spices, Bread Bun, Chutney', 'Tortilla, Cheese, Mushrooms', 'Sausage, Bun, Mustard, Ketchup', 'Flour, Sesame Seeds, Yeast', 'Dough, Spinach, Cheese', 'Flour, Sesame Seeds, Yeast', 'Pork, Pineapple, Onions, Cilantro', 'Dough, Spinach, Cheese', 'Tortilla, Cheese, Mushrooms', 'Potato, Spices, Bread Bun, Chutney', 'Beef, Cheese, Roll, Onions', 'Potato, Spices, Bread Bun, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Sesame Seeds, Yeast', 'Lamb Intestines, Spices, Bread', 'Potato, Spices, Bread Bun, Chutney', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Sesame Seeds, Yeast', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Flour, Red Bean Paste', 'Dough, Spinach, Cheese', 'Beef, Cheese, Roll, Onions', 'Corn, Mayo, Cheese, Chili Powder', 'Flour, Sesame Seeds, Yeast', 'Flour, Sesame Seeds, Yeast', 'Pork, Garlic, Soy Sauce, Sugar', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Sesame Seeds, Yeast', 'Beef, Cheese, Roll, Onions', 'Dough, Spinach, Cheese', 'Semolina, Tamarind, Chickpeas, Spices', 'Sausage, Bun, Mustard, Ketchup', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Potato, Spices, Bread Bun, Chutney', 'Pork, Pineapple, Onions, Cilantro', 'Potato, Spices, Bread Bun, Chutney', 'Pork, Pineapple, Onions, Cilantro', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Corn, Mayo, Cheese, Chili Powder', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Pork, Garlic, Soy Sauce, Sugar', 'Sausage, Bun, Mustard, Ketchup', 'Flour, Sesame Seeds, Yeast', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Sesame Seeds, Yeast', 'Flour, Red Bean Paste', 'Potato, Spices, Bread Bun, Chutney', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Flour, Red Bean Paste', 'Flour, Sesame Seeds, Yeast', 'Semolina, Tamarind, Chickpeas, Spices', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Sesame Seeds, Yeast', 'Roti, Cotton Candy', 'Dough, Spinach, Cheese', 'Sausage, Bun, Mustard, Ketchup', 'Flour, Red Bean Paste', 'Sausage, Bun, Mustard, Ketchup', 'Lamb Intestines, Spices, Bread', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Sausage, Bun, Mustard, Ketchup', 'Tortilla, Cheese, Mushrooms', 'Beef, Cheese, Roll, Onions', 'Flour, Sesame Seeds, Yeast', 'Batter, Sugar, Oil', 'Flour, Red Bean Paste', 'Tortilla, Cheese, Mushrooms', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Beef, Cheese, Roll, Onions', 'Sausage, Bun, Mustard, Ketchup', 'Sausage, Bun, Mustard, Ketchup', 'Pork, Garlic, Soy Sauce, Sugar', 'Corn, Mayo, Cheese, Chili Powder', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Tortilla, Cheese, Mushrooms', 'Flour, Red Bean Paste', 'Flour, Sesame Seeds, Yeast', 'Roti, Cotton Candy', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Batter, Sugar, Oil', 'Potato, Spices, Bread Bun, Chutney', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Red Bean Paste', 'Corn, Mayo, Cheese, Chili Powder', 'Semolina, Tamarind, Chickpeas, Spices', 'Pork, Pineapple, Onions, Cilantro', 'Pork, Garlic, Soy Sauce, Sugar', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Pork, Pineapple, Onions, Cilantro', 'Batter, Sugar, Oil', 'Pork, Pineapple, Onions, Cilantro', 'Roti, Cotton Candy', 'Tortilla, Cheese, Mushrooms', 'Sausage, Bun, Mustard, Ketchup', 'Dough, Spinach, Cheese', 'Lamb Intestines, Spices, Bread', 'Dough, Spinach, Cheese', 'Potato, Spices, Bread Bun, Chutney', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flour, Red Bean Paste', 'Beef, Cheese, Roll, Onions', 'Pork, Pineapple, Onions, Cilantro', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Pork, Pineapple, Onions, Cilantro', 'Batter, Sugar, Oil', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Beef, Cheese, Roll, Onions', 'Pork, Pineapple, Onions, Cilantro', 'Beef, Cheese, Roll, Onions', 'Semolina, Tamarind, Chickpeas, Spices', 'Beef, Cheese, Roll, Onions', 'Corn, Mayo, Cheese, Chili Powder', 'Batter, Sugar, Oil', 'Roti, Cotton Candy', 'Potato, Spices, Bread Bun, Chutney', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Roti, Cotton Candy', 'Roti, Cotton Candy', 'Flour, Sesame Seeds, Yeast', 'Flour, Sesame Seeds, Yeast', 'Batter, Sugar, Oil', 'Lamb Intestines, Spices, Bread', 'Pork, Garlic, Soy Sauce, Sugar', 'Corn, Mayo, Cheese, Chili Powder', 'Semolina, Tamarind, Chickpeas, Spices', 'Sausage, Bun, Mustard, Ketchup', 'Tortilla, Cheese, Mushrooms', 'Flour, Sesame Seeds, Yeast', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Tortilla, Cheese, Mushrooms', 'Tortilla, Cheese, Mushrooms', 'Flour, Sesame Seeds, Yeast', 'Semolina, Tamarind, Chickpeas, Spices', 'Potato, Spices, Bread Bun, Chutney', 'Flour, Red Bean Paste', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Beef, Cheese, Roll, Onions', 'Semolina, Tamarind, Chickpeas, Spices', 'Pork, Pineapple, Onions, Cilantro', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Sesame Seeds, Yeast', 'Sausage, Bun, Mustard, Ketchup', 'Beef, Cheese, Roll, Onions', 'Semolina, Tamarind, Chickpeas, Spices', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Beef, Cheese, Roll, Onions', 'Pork, Garlic, Soy Sauce, Sugar', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Batter, Sugar, Oil', 'Corn, Mayo, Cheese, Chili Powder', 'Dough, Spinach, Cheese', 'Lamb Intestines, Spices, Bread', 'Roti, Cotton Candy', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Batter, Sugar, Oil', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Corn, Mayo, Cheese, Chili Powder', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Dough, Spinach, Cheese', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flour, Sesame Seeds, Yeast', 'Corn, Mayo, Cheese, Chili Powder', 'Roti, Cotton Candy', 'Flour, Sesame Seeds, Yeast', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Semolina, Tamarind, Chickpeas, Spices', 'Dough, Spinach, Cheese', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Potato, Spices, Bread Bun, Chutney', 'Pork, Pineapple, Onions, Cilantro', 'Tortilla, Cheese, Mushrooms', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Flour, Red Bean Paste', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Sausage, Bun, Mustard, Ketchup', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Tortilla, Cheese, Mushrooms', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Pork, Pineapple, Onions, Cilantro', 'Flour, Sesame Seeds, Yeast', 'Lamb Intestines, Spices, Bread', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Sausage, Bun, Mustard, Ketchup', 'Beef, Cheese, Roll, Onions', 'Tortilla, Cheese, Mushrooms', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Beef, Cheese, Roll, Onions', 'Beef, Cheese, Roll, Onions', 'Pork, Pineapple, Onions, Cilantro', 'Flour, Sesame Seeds, Yeast', 'Flour, Red Bean Paste', 'Semolina, Tamarind, Chickpeas, Spices', 'Roti, Cotton Candy', 'Roti, Cotton Candy', 'Flour, Sesame Seeds, Yeast', 'Roti, Cotton Candy', 'Dough, Spinach, Cheese', 'Flour, Sesame Seeds, Yeast', 'Potato, Spices, Bread Bun, Chutney', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Beef, Cheese, Roll, Onions', 'Sausage, Bun, Mustard, Ketchup', 'Batter, Sugar, Oil', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Batter, Sugar, Oil', 'Dough, Spinach, Cheese', 'Lamb Intestines, Spices, Bread', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Flour, Red Bean Paste', 'Beef, Cheese, Roll, Onions', 'Flour, Sesame Seeds, Yeast', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Potato, Spices, Bread Bun, Chutney', 'Batter, Sugar, Oil', 'Potato, Spices, Bread Bun, Chutney', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Red Bean Paste', 'Flour, Red Bean Paste', 'Flour, Red Bean Paste', 'Pork, Garlic, Soy Sauce, Sugar', 'Tortilla, Cheese, Mushrooms', 'Batter, Sugar, Oil', 'Batter, Sugar, Oil', 'Pork, Garlic, Soy Sauce, Sugar', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Pork, Pineapple, Onions, Cilantro', 'Tortilla, Cheese, Mushrooms', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Beef, Cheese, Roll, Onions', 'Sausage, Bun, Mustard, Ketchup', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Lamb Intestines, Spices, Bread', 'Sausage, Bun, Mustard, Ketchup', 'Dough, Spinach, Cheese', 'Pork, Pineapple, Onions, Cilantro', 'Beef, Cheese, Roll, Onions', 'Tortilla, Cheese, Mushrooms', 'Roti, Cotton Candy', 'Pork, Garlic, Soy Sauce, Sugar', 'Lamb Intestines, Spices, Bread', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Flour, Red Bean Paste', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Roti, Cotton Candy', 'Tortilla, Cheese, Mushrooms', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Dough, Spinach, Cheese', 'Tortilla, Cheese, Mushrooms', 'Potato, Spices, Bread Bun, Chutney', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Batter, Sugar, Oil', 'Pork, Garlic, Soy Sauce, Sugar', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Sausage, Bun, Mustard, Ketchup', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Dough, Spinach, Cheese', 'Lamb Intestines, Spices, Bread', 'Potato, Spices, Bread Bun, Chutney', 'Corn, Mayo, Cheese, Chili Powder', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Red Bean Paste', 'Dough, Spinach, Cheese', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flour, Sesame Seeds, Yeast', 'Semolina, Tamarind, Chickpeas, Spices', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Dough, Spinach, Cheese', 'Pork, Pineapple, Onions, Cilantro', 'Lamb Intestines, Spices, Bread', 'Corn, Mayo, Cheese, Chili Powder', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Pineapple, Onions, Cilantro', 'Pork, Pineapple, Onions, Cilantro', 'Dough, Spinach, Cheese', 'Flour, Red Bean Paste', 'Flour, Red Bean Paste', 'Roti, Cotton Candy', 'Tortilla, Cheese, Mushrooms', 'Pork, Garlic, Soy Sauce, Sugar', 'Potato, Spices, Bread Bun, Chutney', 'Tortilla, Cheese, Mushrooms', 'Tortilla, Cheese, Mushrooms', 'Dough, Spinach, Cheese', 'Pork, Garlic, Soy Sauce, Sugar', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Batter, Sugar, Oil', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Pork, Garlic, Soy Sauce, Sugar', 'Dough, Spinach, Cheese', 'Pork, Garlic, Soy Sauce, Sugar', 'Tortilla, Cheese, Mushrooms', 'Batter, Sugar, Oil', 'Beef, Cheese, Roll, Onions', 'Semolina, Tamarind, Chickpeas, Spices', 'Roti, Cotton Candy', 'Dough, Spinach, Cheese', 'Pork, Garlic, Soy Sauce, Sugar', 'Corn, Mayo, Cheese, Chili Powder', 'Semolina, Tamarind, Chickpeas, Spices', 'Potato, Spices, Bread Bun, Chutney', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flour, Sesame Seeds, Yeast', 'Semolina, Tamarind, Chickpeas, Spices', 'Beef, Cheese, Roll, Onions', 'Dough, Spinach, Cheese', 'Semolina, Tamarind, Chickpeas, Spices', 'Dough, Spinach, Cheese', 'Semolina, Tamarind, Chickpeas, Spices', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Lamb Intestines, Spices, Bread', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Roti, Cotton Candy', 'Dough, Spinach, Cheese', 'Batter, Sugar, Oil', 'Semolina, Tamarind, Chickpeas, Spices', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Dough, Spinach, Cheese', 'Potato, Spices, Bread Bun, Chutney', 'Potato, Spices, Bread Bun, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Flour, Red Bean Paste', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Corn, Mayo, Cheese, Chili Powder', 'Flour, Red Bean Paste', 'Batter, Sugar, Oil', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Roti, Cotton Candy', 'Potato, Spices, Bread Bun, Chutney', 'Flour, Red Bean Paste', 'Batter, Sugar, Oil', 'Dough, Spinach, Cheese', 'Pork, Garlic, Soy Sauce, Sugar', 'Potato, Spices, Bread Bun, Chutney', 'Batter, Sugar, Oil', 'Potato, Spices, Bread Bun, Chutney', 'Semolina, Tamarind, Chickpeas, Spices', 'Dough, Spinach, Cheese', 'Roti, Cotton Candy', 'Tortilla, Cheese, Mushrooms', 'Corn, Mayo, Cheese, Chili Powder', 'Sausage, Bun, Mustard, Ketchup', 'Sausage, Bun, Mustard, Ketchup', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Sesame Seeds, Yeast', 'Sausage, Bun, Mustard, Ketchup', 'Pork, Pineapple, Onions, Cilantro', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Beef, Cheese, Roll, Onions', 'Pork, Garlic, Soy Sauce, Sugar', 'Corn, Mayo, Cheese, Chili Powder', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flour, Red Bean Paste', 'Roti, Cotton Candy', 'Beef, Cheese, Roll, Onions', 'Dough, Spinach, Cheese', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Potato, Spices, Bread Bun, Chutney', 'Roti, Cotton Candy', 'Sausage, Bun, Mustard, Ketchup', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flour, Red Bean Paste', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Corn, Mayo, Cheese, Chili Powder', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Flour, Red Bean Paste', 'Flour, Red Bean Paste', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Lamb Intestines, Spices, Bread', 'Pork, Garlic, Soy Sauce, Sugar', 'Pork, Garlic, Soy Sauce, Sugar', 'Semolina, Tamarind, Chickpeas, Spices', 'Semolina, Tamarind, Chickpeas, Spices', 'Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts', 'Octopus, Flour Batter, Bonito Flakes, Green Onions', 'Dough, Spinach, Cheese', 'Flatbread, Egg, Chicken, Onions, Chutney', 'Dough, Spinach, Cheese', 'Noodles, Pork, Cabbage, Yakisoba Sauce', 'Corn, Mayo, Cheese, Chili Powder', 'Tortilla, Cheese, Mushrooms', 'Pork, Pineapple, Onions, Cilantro', 'Flour, Red Bean Paste', 'Flour, Red Bean Paste', 'Sausage, Bun, Mustard, K

I got partial output of what I wanted- I needed a list of all unique ingredients but not in ['octopus, flour, onions', 'Potato, spice, oil']  this format

In [7]:
"""l=[]
for i in df["Ingredients"]:
    for j in i.split(", "):
        l.append(j)"""

l=list(j for i in df["Ingredients"].dropna() for j in i.split(", "))

idf= pd.DataFrame(l,columns=["Ingredient"])
idf=idf.drop_duplicates()

ingredient_count= idf["Ingredient"].nunique()
print(ingredient_count)
Statistics["Counts"]["Ingredients_count"]= ingredient_count
display(idf)
display(Statistics)

69

          Ingredient
0            Octopus
1       Flour Batter
2      Bonito Flakes
3       Green Onions
4             Potato
...              ...
15614        Skewers
15615        Lentils
15616           Rice
15617          Pasta
15618   Tomato Sauce

[69 rows x 1 columns]

{'Counts': {'Country_city_Dimension': {'Country': 11,
   'City': 25,
   'Country city pairs': 25},
  'Ingredients_count': 69}}

In [8]:
#Unique Dishes

dish_df= df["Dish Name"].drop_duplicates().sort_values(ascending=True).reset_index(drop=True)
dish_entries= df.groupby("Dish Name")['Dish Name'].count()
display(dish_df)
display(dish_entries)

0             Bunny Chow
1                  Elote
2                Falafel
3            Funnel Cake
4                Gözleme
5                Hot Dog
6             Kathi Roll
7                Kokoreç
8                Koshari
9               Manakish
10              Moo Ping
11           Okonomiyaki
12              Pad Thai
13             Pani Puri
14    Philly Cheesesteak
15            Quesadilla
16          Roti Sai Mai
17              Shawarma
18                 Simit
19                  Suya
20       Tacos al Pastor
21               Taiyaki
22              Takoyaki
23              Vada Pav
24              Yakisoba
Name: Dish Name, dtype: str

Dish Name
Bunny Chow             58
Elote                 223
Falafel                49
Funnel Cake           206
Gözleme               234
Hot Dog               210
Kathi Roll            213
Kokoreç               194
Koshari                57
Manakish               56
Moo Ping              246
Okonomiyaki            50
Pad Thai              235
Pani Puri             239
Philly Cheesesteak    205
Quesadilla            225
Roti Sai Mai          241
Shawarma               62
Simit                 222
Suya                   51
Tacos al Pastor       212
Taiyaki               271
Takoyaki              233
Vada Pav              230
Yakisoba              278
Name: Dish Name, dtype: int64

In [9]:
# Top 10 Costliest Foods

costlyfoods= df.sort_values(by="Typical Price (USD)", ascending=False).drop_duplicates().head(10)
display(costlyfoods)

,Dish Name,Country,Region/City,Ingredients,Description,Cooking Method,Typical Price (USD),Vegetarian
4304,Okonomiyaki,Japan,Hiroshima,"Cabbage, Flour, Pork, Sauce, Mayo",Savory pancake with varied fillings and toppings.,Pan-Fried,5.00,No
935,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,5.00,Yes
2024,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,5.00,Yes
2542,Taiyaki,Japan,Kyoto,"Flour, Red Bean Paste",Golden brown and fluffy with a soft interior.,Baked,5.00,Yes
2065,Moo Ping,Thailand,Chiang Mai,"Pork, Garlic, Soy Sauce, Sugar",Charred to perfection with a smoky flavor.,Grilled,4.99,No
2220,Kokoreç,Turkey,Izmir,"Lamb Intestines, Spices, Bread",Charred to perfection with a smoky flavor.,Grilled,4.99,No
1347,Philly Cheesesteak,USA,Philadelphia,"Beef, Cheese, Roll, Onions",Charred to perfection with a smoky flavor.,Grilled,4.99,No
993,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,4.99,No
1452,Gözleme,Turkey,Ankara,"Dough, Spinach, Cheese",Charred to perfection with a smoky flavor.,Grilled,4.99,Yes
945,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,4.99,Yes

### Highest Priced Entry for each food

In [10]:
Highest_per_food = (
    df.loc[
        df.groupby("Dish Name")["Typical Price (USD)"].idxmax()
    ]
    .sort_values("Typical Price (USD)", ascending=False)
    .reset_index(drop=True)
)
display(Highest_per_food)

,Dish Name,Country,Region/City,Ingredients,Description,Cooking Method,Typical Price (USD),Vegetarian
0,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,5.00,Yes
1,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,5.00,Yes
2,Taiyaki,Japan,Kyoto,"Flour, Red Bean Paste",Golden brown and fluffy with a soft interior.,Baked,5.00,Yes
3,Okonomiyaki,Japan,Hiroshima,"Cabbage, Flour, Pork, Sauce, Mayo",Savory pancake with varied fillings and toppings.,Pan-Fried,5.00,No
4,Kokoreç,Turkey,Izmir,"Lamb Intestines, Spices, Bread",Charred to perfection with a smoky flavor.,Grilled,4.99,No
5,Moo Ping,Thailand,Chiang Mai,"Pork, Garlic, Soy Sauce, Sugar",Charred to perfection with a smoky flavor.,Grilled,4.99,No
6,Funnel Cake,USA,Texas,"Batter, Sugar, Oil","Crispy and hot, often served with sauces or ch...",Fried,4.99,Yes
7,Gözleme,Turkey,Ankara,"Dough, Spinach, Cheese",Charred to perfection with a smoky flavor.,Grilled,4.99,Yes
8,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,4.99,No
9,Roti Sai Mai,Thailand,Ayutthaya,"Roti, Cotton Candy",Put together fresh with a mix of flavors and t...,Assembled,4.99,Yes
10,Tacos al Pastor,Mexico,Mexico City,"Pork, Pineapple, Onions, Cilantro",Charred to perfection with a smoky flavor.,Grilled,4.99,No
11,Quesadilla,Mexico,Puebla,"Tortilla, Cheese, Mushrooms",Charred to perfection with a smoky flavor.,Grilled,4.99,Yes
12,Philly Cheesesteak,USA,Philadelphia,"Beef, Cheese, Roll, Onions",Charred to perfection with a smoky flavor.,Grilled,4.99,No
13,Simit,Turkey,Istanbul,"Flour, Sesame Seeds, Yeast",Golden brown and fluffy with a soft interior.,Baked,4.98,Yes
14,Pad Thai,Thailand,Bangkok,"Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,4.96,Yes
15,Takoyaki,Japan,Osaka,"Octopus, Flour Batter, Bonito Flakes, Green On...","Crispy and hot, often served with sauces or ch...",Fried,4.95,No
16,Yakisoba,Japan,Tokyo,"Noodles, Pork, Cabbage, Yakisoba Sauce",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,4.95,No
17,Pani Puri,India,Delhi,"Semolina, Tamarind, Chickpeas, Spices",Put together fresh with a mix of flavors and t...,Assembled,4.94,Yes
18,Hot Dog,USA,New York,"Sausage, Bun, Mustard, Ketchup",Charred to perfection with a smoky flavor.,Grilled,4.94,No
19,Shawarma,Lebanon,Beirut,"Meat, Pita Bread, Garlic Sauce, Pickles",Sliced meat wrapped in pita bread with garlic ...,Grilled,4.50,No
20,Bunny Chow,South Africa,Durban,"Bread, Curry",Hollowed bread filled with curry.,Stewed,3.50,No
21,Falafel,Israel,Tel Aviv,"Chickpeas, Herbs, Spices, Tahini Sauce",Deep-fried chickpea balls served in pita with ...,Fried,3.00,Yes
22,Koshari,Egypt,Cairo,"Lentils, Rice, Pasta, Tomato Sauce, Onions",A hearty mix of grains topped with spicy tomat...,Boiled,2.80,Yes
23,Manakish,Lebanon,Tripoli,"Flatbread, Za'atar, Olive Oil",Flatbread topped with za'atar and olive oil.,Baked,2.50,Yes
24,Suya,Nigeria,Lagos,"Beef, Spices, Skewers",Spicy meat skewers grilled to perfection.,Grilled,2.50,No

### nth Highest and nth Lowest Price of each Dish

In [11]:
nth_highest = (
    df[df.groupby("Dish Name")["Typical Price (USD)"]
       .rank(method="dense", ascending=False) == 2].reset_index(drop=True)
)

nth_lowest = (
    df[df.groupby("Dish Name")["Typical Price (USD)"]
       .rank(method="dense", ascending=True) == 3].reset_index(drop=True)
)

display(nth_highest)
display(nth_lowest)

,Dish Name,Country,Region/City,Ingredients,Description,Cooking Method,Typical Price (USD),Vegetarian
0,Roti Sai Mai,Thailand,Ayutthaya,"Roti, Cotton Candy",Put together fresh with a mix of flavors and t...,Assembled,4.98,Yes
1,Tacos al Pastor,Mexico,Mexico City,"Pork, Pineapple, Onions, Cilantro",Charred to perfection with a smoky flavor.,Grilled,4.98,No
2,Kokoreç,Turkey,Izmir,"Lamb Intestines, Spices, Bread",Charred to perfection with a smoky flavor.,Grilled,4.98,No
3,Pad Thai,Thailand,Bangkok,"Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,4.94,Yes
4,Philly Cheesesteak,USA,Philadelphia,"Beef, Cheese, Roll, Onions",Charred to perfection with a smoky flavor.,Grilled,4.95,No
5,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,4.99,Yes
6,Yakisoba,Japan,Tokyo,"Noodles, Pork, Cabbage, Yakisoba Sauce",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,4.93,No
7,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,4.99,Yes
8,Taiyaki,Japan,Kyoto,"Flour, Red Bean Paste",Golden brown and fluffy with a soft interior.,Baked,4.99,Yes
9,Quesadilla,Mexico,Puebla,"Tortilla, Cheese, Mushrooms",Charred to perfection with a smoky flavor.,Grilled,4.92,Yes
10,Kokoreç,Turkey,Izmir,"Lamb Intestines, Spices, Bread",Charred to perfection with a smoky flavor.,Grilled,4.98,No
11,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,4.96,No
12,Moo Ping,Thailand,Chiang Mai,"Pork, Garlic, Soy Sauce, Sugar",Charred to perfection with a smoky flavor.,Grilled,4.98,No
13,Hot Dog,USA,New York,"Sausage, Bun, Mustard, Ketchup",Charred to perfection with a smoky flavor.,Grilled,4.91,No
14,Takoyaki,Japan,Osaka,"Octopus, Flour Batter, Bonito Flakes, Green On...","Crispy and hot, often served with sauces or ch...",Fried,4.91,No
15,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,4.97,Yes
16,Funnel Cake,USA,Texas,"Batter, Sugar, Oil","Crispy and hot, often served with sauces or ch...",Fried,4.97,Yes
17,Pani Puri,India,Delhi,"Semolina, Tamarind, Chickpeas, Spices",Put together fresh with a mix of flavors and t...,Assembled,4.86,Yes
18,Gözleme,Turkey,Ankara,"Dough, Spinach, Cheese",Charred to perfection with a smoky flavor.,Grilled,4.96,Yes
19,Simit,Turkey,Istanbul,"Flour, Sesame Seeds, Yeast",Golden brown and fluffy with a soft interior.,Baked,4.95,Yes
20,Funnel Cake,USA,Texas,"Batter, Sugar, Oil","Crispy and hot, often served with sauces or ch...",Fried,4.97,Yes
21,Philly Cheesesteak,USA,Philadelphia,"Beef, Cheese, Roll, Onions",Charred to perfection with a smoky flavor.,Grilled,4.95,No

,Dish Name,Country,Region/City,Ingredients,Description,Cooking Method,Typical Price (USD),Vegetarian
0,Tacos al Pastor,Mexico,Mexico City,"Pork, Pineapple, Onions, Cilantro",Charred to perfection with a smoky flavor.,Grilled,0.32,No
1,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,0.27,Yes
2,Kokoreç,Turkey,Izmir,"Lamb Intestines, Spices, Bread",Charred to perfection with a smoky flavor.,Grilled,0.23,No
3,Gözleme,Turkey,Ankara,"Dough, Spinach, Cheese",Charred to perfection with a smoky flavor.,Grilled,0.37,Yes
4,Quesadilla,Mexico,Puebla,"Tortilla, Cheese, Mushrooms",Charred to perfection with a smoky flavor.,Grilled,0.25,Yes
5,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,0.30,Yes
6,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,0.24,No
7,Pani Puri,India,Delhi,"Semolina, Tamarind, Chickpeas, Spices",Put together fresh with a mix of flavors and t...,Assembled,0.28,Yes
8,Taiyaki,Japan,Kyoto,"Flour, Red Bean Paste",Golden brown and fluffy with a soft interior.,Baked,0.25,Yes
9,Pad Thai,Thailand,Bangkok,"Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,0.22,Yes
10,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,0.24,No
11,Hot Dog,USA,New York,"Sausage, Bun, Mustard, Ketchup",Charred to perfection with a smoky flavor.,Grilled,0.30,No
12,Takoyaki,Japan,Osaka,"Octopus, Flour Batter, Bonito Flakes, Green On...","Crispy and hot, often served with sauces or ch...",Fried,0.29,No
13,Philly Cheesesteak,USA,Philadelphia,"Beef, Cheese, Roll, Onions",Charred to perfection with a smoky flavor.,Grilled,0.27,No
14,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,0.27,Yes
15,Moo Ping,Thailand,Chiang Mai,"Pork, Garlic, Soy Sauce, Sugar",Charred to perfection with a smoky flavor.,Grilled,0.33,No
16,Roti Sai Mai,Thailand,Ayutthaya,"Roti, Cotton Candy",Put together fresh with a mix of flavors and t...,Assembled,0.32,Yes
17,Funnel Cake,USA,Texas,"Batter, Sugar, Oil","Crispy and hot, often served with sauces or ch...",Fried,0.29,Yes
18,Simit,Turkey,Istanbul,"Flour, Sesame Seeds, Yeast",Golden brown and fluffy with a soft interior.,Baked,0.24,Yes
19,Yakisoba,Japan,Tokyo,"Noodles, Pork, Cabbage, Yakisoba Sauce",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,0.28,No
20,Roti Sai Mai,Thailand,Ayutthaya,"Roti, Cotton Candy",Put together fresh with a mix of flavors and t...,Assembled,0.32,Yes
21,Pani Puri,India,Delhi,"Semolina, Tamarind, Chickpeas, Spices",Put together fresh with a mix of flavors and t...,Assembled,0.28,Yes

### Find top three costliest dishes per country

In [12]:
highest_per_dish = df.loc[
    df.groupby(["Country", "Dish Name"])["Typical Price (USD)"].idxmax()
]

highest_per_dish["Price_rank"]= (highest_per_dish.groupby("Country")["Typical Price (USD)"]
                                 .rank(method="dense", ascending=False))

top_three_dishes = (
    highest_per_dish[
        highest_per_dish["Price_rank"].isin([1, 2, 3])
    ]
    .sort_values(["Country", "Price_rank"])
    .reset_index(drop=True)
)

display(top_three_dishes)

,Dish Name,Country,Region/City,Ingredients,Description,Cooking Method,Typical Price (USD),Vegetarian,Price_rank
0,Koshari,Egypt,Cairo,"Lentils, Rice, Pasta, Tomato Sauce, Onions",A hearty mix of grains topped with spicy tomat...,Boiled,2.80,Yes,1.0
1,Vada Pav,India,Mumbai,"Potato, Spices, Bread Bun, Chutney","Crispy and hot, often served with sauces or ch...",Fried,5.00,Yes,1.0
2,Kathi Roll,India,Kolkata,"Flatbread, Egg, Chicken, Onions, Chutney",Charred to perfection with a smoky flavor.,Grilled,4.99,No,2.0
3,Pani Puri,India,Delhi,"Semolina, Tamarind, Chickpeas, Spices",Put together fresh with a mix of flavors and t...,Assembled,4.94,Yes,3.0
4,Falafel,Israel,Tel Aviv,"Chickpeas, Herbs, Spices, Tahini Sauce",Deep-fried chickpea balls served in pita with ...,Fried,3.00,Yes,1.0
5,Okonomiyaki,Japan,Hiroshima,"Cabbage, Flour, Pork, Sauce, Mayo",Savory pancake with varied fillings and toppings.,Pan-Fried,5.00,No,1.0
6,Taiyaki,Japan,Kyoto,"Flour, Red Bean Paste",Golden brown and fluffy with a soft interior.,Baked,5.00,Yes,1.0
7,Takoyaki,Japan,Osaka,"Octopus, Flour Batter, Bonito Flakes, Green On...","Crispy and hot, often served with sauces or ch...",Fried,4.95,No,2.0
8,Yakisoba,Japan,Tokyo,"Noodles, Pork, Cabbage, Yakisoba Sauce",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,4.95,No,2.0
9,Shawarma,Lebanon,Beirut,"Meat, Pita Bread, Garlic Sauce, Pickles",Sliced meat wrapped in pita bread with garlic ...,Grilled,4.50,No,1.0
10,Manakish,Lebanon,Tripoli,"Flatbread, Za'atar, Olive Oil",Flatbread topped with za'atar and olive oil.,Baked,2.50,Yes,2.0
11,Elote,Mexico,Guadalajara,"Corn, Mayo, Cheese, Chili Powder","Soft and juicy, sometimes charred for flavor.",Boiled/Grilled,5.00,Yes,1.0
12,Quesadilla,Mexico,Puebla,"Tortilla, Cheese, Mushrooms",Charred to perfection with a smoky flavor.,Grilled,4.99,Yes,2.0
13,Tacos al Pastor,Mexico,Mexico City,"Pork, Pineapple, Onions, Cilantro",Charred to perfection with a smoky flavor.,Grilled,4.99,No,2.0
14,Suya,Nigeria,Lagos,"Beef, Spices, Skewers",Spicy meat skewers grilled to perfection.,Grilled,2.50,No,1.0
15,Bunny Chow,South Africa,Durban,"Bread, Curry",Hollowed bread filled with curry.,Stewed,3.50,No,1.0
16,Moo Ping,Thailand,Chiang Mai,"Pork, Garlic, Soy Sauce, Sugar",Charred to perfection with a smoky flavor.,Grilled,4.99,No,1.0
17,Roti Sai Mai,Thailand,Ayutthaya,"Roti, Cotton Candy",Put together fresh with a mix of flavors and t...,Assembled,4.99,Yes,1.0
18,Pad Thai,Thailand,Bangkok,"Rice Noodles, Tofu, Eggs, Peanuts, Bean Sprouts",Quickly tossed in a hot pan with bold flavors.,Stir-Fried,4.96,Yes,2.0
19,Gözleme,Turkey,Ankara,"Dough, Spinach, Cheese",Charred to perfection with a smoky flavor.,Grilled,4.99,Yes,1.0
20,Kokoreç,Turkey,Izmir,"Lamb Intestines, Spices, Bread",Charred to perfection with a smoky flavor.,Grilled,4.99,No,1.0
21,Simit,Turkey,Istanbul,"Flour, Sesame Seeds, Yeast",Golden brown and fluffy with a soft interior.,Baked,4.98,Yes,2.0
22,Funnel Cake,USA,Texas,"Batter, Sugar, Oil","Crispy and hot, often served with sauces or ch...",Fried,4.99,Yes,1.0
23,Philly Cheesesteak,USA,Philadelphia,"Beef, Cheese, Roll, Onions",Charred to perfection with a smoky flavor.,Grilled,4.99,No,1.0
24,Hot Dog,USA,New York,"Sausage, Bun, Mustard, Ketchup",Charred to perfection with a smoky flavor.,Grilled,4.94,No,2.0

### Find the country whose most expensive dish is costlier than all other

In [13]:
#There are multiple dishes which are costlier - taking the one based on price
most_expensive = highest_per_dish.loc[
    highest_per_dish["Typical Price (USD)"].idxmax()
]

print(most_expensive["Country"])

India

### Calculate each dish’s percentage difference from the country average

In [14]:
new_df = df.copy()

new_df["country_average"] = (
    new_df.groupby("Country")["Typical Price (USD)"]
          .transform("mean").reset_index(drop=True)
)

new_df["dish_avg"] = (
    new_df.groupby("Dish Name")["Typical Price (USD)"]
          .transform("mean").reset_index(drop=True)
)

new_df["diff_from_avg"] = (
    (
        abs(new_df["dish_avg"] - new_df["country_average"])
    )
    / new_df["country_average"]
    * 100
).round(2)

display(new_df[["Dish Name", "diff_from_avg"]])

        Dish Name  diff_from_avg
0        Takoyaki           5.30
1        Vada Pav           1.84
2     Funnel Cake           3.09
3      Kathi Roll           0.58
4        Pad Thai           0.31
...           ...            ...
4495      Koshari           0.00
4496      Koshari           0.00
4497      Koshari           0.00
4498      Koshari           0.00
4499         Suya           0.00

[4500 rows x 2 columns]

### Find countries with above-average prices and below-average dish counts

In [15]:
new_df= df.copy()
new_df["average_price"]= new_df.groupby("Country" )["Typical Price (USD)"].transform("mean")
new_df["dish_count"]= new_df.groupby("Country")["Dish Name"].transform("nunique")

result= new_df[
    (new_df["average_price"]>new_df["average_price"].mean()) &
    (new_df["dish_count"]<new_df["dish_count"].mean())
]

result= result[["Country","average_price","dish_count"]].drop_duplicates().reset_index(drop=True)
print(f"Average price: {new_df['average_price'].mean()}")
print(f"Average Dish Count: {new_df['dish_count'].mean()}")
display(result)

Average price: 2.657428888888889
Average Dish Count: 3.063111111111111

        Country  average_price  dish_count
0        Israel       3.000000           1
1       Lebanon       3.550847           2
2  South Africa       3.500000           1
3         Egypt       2.800000           1

### Create a summary table containing country, dish count, average price, minimum price, and maximum price

In [16]:
country_ingredients = {}

for country, group in df.groupby("Country"):
    ingredients = []

    for ingredient_text in group["Ingredients"].dropna():
        ingredients.extend(
            ingredient.strip()
            for ingredient in ingredient_text.split(",")
        )

    country_ingredients[country] = ingredients

print(country_ingredients)

{'Egypt': ['Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions', 'Lentils', 'Rice', 'Pasta', 'Tomato Sauce', 'Onions'], 'India': ['Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Flatbread', 'Egg', 'Chicken', 'Onions', 'Chutney', 'Semolina', 'Tamarind', 'Chickpeas', 'Spices', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Potato', 'Spices', 'Bread Bun', 'Chutney', 'Semolina', 'Ta

### Find the most common ingredient for each country.

In [18]:
country_ingredients = {}

for country, group in df.groupby("Country"):
    ingredient_counts = {}

    for ingredient_text in group["Ingredients"].dropna():
        for ingredient in ingredient_text.split(","):
            ingredient = ingredient.strip()

            if ingredient in ingredient_counts:
                ingredient_counts[ingredient] += 1
            else:
                ingredient_counts[ingredient] = 1

    country_ingredients[country] = ingredient_counts


most_common = {}

for country, ingredient_counts in country_ingredients.items():
    common_ingredient = None
    highest_count = 0

    for ingredient, count in ingredient_counts.items():
        if count > highest_count:
            highest_count = count
            common_ingredient = ingredient

    most_common[country] = {
        "ingredient": common_ingredient,
        "count": highest_count
    }

most_common_df = pd.DataFrame.from_dict(
    most_common,
    orient="index"
).reset_index()

most_common_df = most_common_df.rename(columns={"index": "Country"})

display(most_common_df)

         Country ingredient  count
0          Egypt    Lentils     57
1          India     Spices    469
2         Israel  Chickpeas     49
3          Japan      Flour    321
4        Lebanon       Meat     62
5         Mexico     Cheese    448
6        Nigeria       Beef     51
7   South Africa      Bread     58
8       Thailand       Pork    246
9         Turkey      Dough    234
10           USA    Sausage    210

In [19]:
ingredients_df = (
    df[["Country", "Ingredients"]]
    .dropna()
    .assign(Ingredient=lambda x: x["Ingredients"].str.split(","))
    .explode("Ingredient")
)

ingredients_df["Ingredient"] = ingredients_df["Ingredient"].str.strip()

ingredient_counts = (
    ingredients_df
    .groupby(["Country", "Ingredient"])
    .size()
    .reset_index(name="count")
)

most_common_df = (
    ingredient_counts.loc[
        ingredient_counts.groupby("Country")["count"].idxmax()
    ]
    .sort_values("Country")
    .reset_index(drop=True)
)

display(most_common_df)

         Country    Ingredient  count
0          Egypt       Lentils     57
1          India        Spices    469
2         Israel     Chickpeas     49
3          Japan         Flour    321
4        Lebanon  Garlic Sauce     62
5         Mexico        Cheese    448
6        Nigeria          Beef     51
7   South Africa         Bread     58
8       Thailand        Garlic    246
9         Turkey        Cheese    234
10           USA           Bun    210